name = "JGE"
uuid = "9f14b124-c50e-4008-a7d4-969b2a6cd68a"
authors = ["Cédric Belmant"]
version = "0.1.0"

[deps]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
